---
- hosts: nodes
  become: true 
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: starting the service
      service:
        name: apache2
        state: stopped
        enabled: false
    - name: create html file
      copy:
        content: "<h1> welcome to capgemini </h1>"
        dest: /var/www/html/index.html    
