---
- hosts: nodes
  vars: 
   user1: saif2
  tasks:
      - name: create a user named {{ user1 }}
        user:
          name: "{{ user1 }}"
          state: present
      - name: add multple users
        user:
          name: "{{ item }}"
          state: present
        with_items:
             - saif3
             - saif4
             - saif5
             - saif6
